src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\ManyToMany(targetEntity: ContenuPanier::class, mappedBy: 'produit')]
    private Collection $contenuPaniers;

    public function __construct()
    {
        $this->contenuPaniers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection<int, ContenuPanier>
     */
    public function getContenuPaniers(): Collection
    {
        return $this->contenuPaniers;
    }

    public function addContenuPanier(ContenuPanier $contenuPanier): static
    {
        if (!$this->contenuPaniers->contains($contenuPanier)) {
            $this->contenuPaniers->add($contenuPanier);
            $contenuPanier->addProduit($this);
        }

        return $this;
    }

    public function removeContenuPanier(ContenuPanier $contenuPanier): static
    {
        if ($this->contenuPaniers->removeElement($contenuPanier)) {
            $contenuPanier->removeProduit($this);
        }

        return $this;
    }
    #[ORM\PostRemove]
    public function deleteImage(): static
    {
        if ($this->photo != null) {
            unlink(__DIR__ . '/../../public/uploads/' . $this->photo);
        }

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('Description')
            ->add('prix')
            ->add('stock')
            ->add('photo', FileType::class, [
                'label' => 'image (jpg, png)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using attributes
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024M',
                        'mimeTypes' => [
                            'image/jpg',
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image',
                    ])
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\ContenuPanier;
use App\Entity\Panier;
use App\Entity\Produit;
use App\Entity\User;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'app_produit_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, TranslatorInterface $translator): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form->get('photo')->getData();

            if($imageFile) {
                $newFilename = uniqid() . '.' . $imageFile->guessExtension();
                try {
                    $imageFile->move(
                        $this->getParameter('upload_directory'),
                        $newFilename
                    );
                } catch(FileException $e) {
                    $this->addFlash('danger', $translator->trans('product.file', [], 'message'));
                    return $this->redirectToRoute('app_produit_index');
                }
                $produit->setPhoto($newFilename);
            }
            $entityManager->persist($produit);
            $entityManager->flush();
            $this->addFlash('success', $translator->trans('product.new', [], 'message'));

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }
    #[Route('/add/{id}', name: 'app_produit_add', methods: ['GET'])]
    public function add(Produit $produit, EntityManagerInterface $entityManager, TranslatorInterface $translator): Response
    {
        $contenuPanier = new ContenuPanier();

        $contenuPanier->addProduit($produit);
        $contenuPanier->setQquantite(1);
        $contenuPanier->setDate(new \DateTime());

        /** @var User $user */
        $user = $this->getUser();

        $panierValide = $entityManager->getRepository(Panier::class)->findPanierActif($user);

        if($panierValide == null){
            $panierValide = new Panier();
            $panierValide->setUserPanier($user);
            $panierValide->setEtat(false);
            $entityManager->persist($panierValide);
        }

        $panierValide->addContenuPanier($contenuPanier);
        $entityManager->persist($contenuPanier);
        $entityManager->flush();
        $this->addFlash('success', $translator->trans('product.add', [], 'message'));

        return $this->redirectToRoute('app_contenu_panier_index');
    }

    /**
     * @throws Exception
     */
    #[Route('/{id}/edit', name: 'app_produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit, EntityManagerInterface $entityManager, TranslatorInterface $translator): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash('success', $translator->trans('product.edit', [], 'message'));

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit, EntityManagerInterface $entityManager, TranslatorInterface $translator): Response
    {
        if($this->isCsrfTokenValid('delete' . $produit->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($produit);
            $entityManager->flush();
            $this->addFlash('success', $translator->trans('product.delete', [], 'message'));
        }

        return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/produit/_delete_form.html.twig
{% trans_default_domain 'product' %}
<form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}"
      onsubmit="return confirm({{ 'message.delete'|trans({}, 'cart_content') }});">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn-danger">{{ 'btn.delete'|trans({}, 'commons') }}</button>
</form>
<style>
    .btn-danger {
        background-color: #dc3545;
    }
</style>

templates/produit/_form.html.twig
{% trans_default_domain 'commons' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('btn.save'|trans) }}</button>
{{ form_end(form) }}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain 'product' %}

{% block title %}{{ 'edit.title'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'edit.title'|trans }}</h1>
    <div class="form">
        {{ include('produit/_form.html.twig', {'button_label': 'btn.update'|trans({}, 'commons')    }) }}
        {{ include('produit/_delete_form.html.twig') }}
        <a href="{{ path('app_produit_index') }}">{{ 'btn.back'|trans({}, 'commons') }}</a>
    </div>
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain 'product' %}

{% block title %}{{ 'index.title'|trans }}{% endblock %}

{% block body %}
    <style>
        .featured-product {
            width: 100%;
            height: 300px;
            background-color: #f0f0f0;
            text-align: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            margin-bottom: 20px;
        }

        .featured-product img {
            max-width: 80%;
            max-height: 200px;
            border-radius: 10px;
        }

        .featured-product-title {
            font-size: 1.5rem;
            font-weight: bold;
            margin-top: 10px;
        }

        .featured-product-price {
            font-size: 1.2rem;
            margin-top: 10px;
        }

        .container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        .card {
            width: 200px;
            height: 300px;
            margin: 10px;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
            border-radius: 10px;
            display: inline-block;
        }

        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }

        .card img {
            border-radius: 10px 10px 0 0;
            width: 100%;
            height: 120px;
            object-fit: cover;
        }

        .card-body {
            padding: 10px;
        }

        .card-title {
            font-weight: bold;
            font-size: 1rem;
            margin-bottom: 5px;
        }

        .card-text {
            font-size: 0.8rem;
            margin-bottom: 5px;
        }

       .btn {
            display: inline-block;
            padding: 8px 16px;
            background-color: #4CAF50;
            color: white;
            text-align: center;
            font-size: 14px;
            border-radius: 4px;
            transition: background-color 0.3s;
            text-decoration: none;
            margin-right: 10px;
        }

        .btn:hover {
            background-color: #45a049;
        }

        .no-product {
            text-align: center;
            margin-top: 20px;
        }
    </style>

    <h1 class="text-center">{{ 'index.title'|trans }}</h1>

    {% if produits|length > 0 %}
        {% set featuredProduct = produits[0] %}
        <div class="featured-product">
            <img src="{{ asset('uploads/' ~ featuredProduct.Photo) }}" alt="logo du produit">
            <div class="featured-product-title">{{ featuredProduct.nom }}</div>
            <div class="featured-product-price">{{ featuredProduct.prix }}€</div>
             <a href="{{ path('app_produit_show', {'id': featuredProduct.id}) }}" class="btn">{{ 'btn.show'|trans({}, 'commons') }}</a>

        </div>
    {% else %}
        <p class="no-product">{{ 'index.empty'|trans }}.</p>
    {% endif %}

    <div class="container">
        {% if produits|length > 1 %}
            {% for produit in produits[1:] %}
                <div class="card">
                    <img src="{{ asset('uploads/' ~ produit.Photo) }}" alt="logo du produit">
                    <div class="card-body">
                        <h5>{{ produit.nom }}</h5>
                        <p>{{ produit.Description }}</p>
                        <p>{{ produit.prix }}€</p>
                        <p>Stock: {{ produit.stock }}</p>
                        <a href="{{ path('app_produit_show', {'id': produit.id}) }}" class="btn">{{ 'btn.show'|trans({}, 'commons') }}</a>
                        {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %}
                            <a href="{{ path('app_produit_edit', {'id': produit.id}) }}" class="btn">{{ 'btn.edit'|trans({}, 'commons') }}</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %}
        <div class="text-center mt-4">
            <a href="{{ path('app_produit_new') }}" class="btn btn-success">{{ 'index.new'|trans }}</a>
        </div>
    {% endif %}
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain 'product' %}

{% block title %}{{ 'new.title'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'new.title'|trans }}</h1>
    <div class="form">
        {{ include('produit/_form.html.twig') }}
        <a href="{{ path('app_produit_index') }}">{{ 'btn.back'|trans({}, 'commons') }}</a>
    </div>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain 'product' %}

{% block title %}{{ produit.nom }}{% endblock %}

{% block stylesheets %}
    <style>
        /* Styles spécifiques à la card */
        .card {
            border: 1px solid #ccc;
            border-radius: 5px;
            margin: 20px auto;
            max-width: 400px; /* Réduire la largeur de la card */
            padding: 10px; /* Réduire l'espace à l'intérieur de la card */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .card-header {
            background-color: #f0f0f0;
            border-bottom: 1px solid #ccc;
            padding: 10px;
            margin-bottom: 10px;
        }

        .card-body {
            padding: 0;
        }

        .card-table {
            width: 100%;
            border-collapse: collapse;
        }

        .card-table th,
        .card-table td {
            padding: 8px; /* Réduire la taille de la cellule */
            border-bottom: 1px solid #ccc;
        }

        .card-img {
            max-width: 100%;
            height: auto;
            margin-bottom: 10px; /* Ajouter un peu d'espace en bas de l'image */
        }

        .btn {
            display: inline-block;
            padding: 8px 16px; /* Réduire la taille des boutons */
            margin-right: 10px;
            border: none;
            border-radius: 5px;
            text-decoration: none;
            color: #fff;
            background-color: #007bff;
            cursor: pointer;
        }

        .btn.btn-primary {
            background-color: #007bff;
        }

        .btn.btn-success {
            background-color: #28a745;
        }

        .btn.btn-warning {
            background-color: #ffc107;
        }

        .btn.btn-danger {
            background-color: #dc3545;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="card">
        <h1 class="card-header">{{ produit.nom }}</h1>
        <div class="card-body">
            <table class="card-table">
                <tbody>
                    <tr>
                        <th>{{ 'tab.description'|trans({}, 'commons') }}</th>
                        <td>{{ produit.Description }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'tab.price'|trans({}, 'commons') }}</th>
                        <td>{{ produit.prix }}€</td>
                    </tr>
                    <tr>
                        <th>{{ 'tab.stock'|trans({}, 'commons') }}</th>
                        <td>{{ produit.stock }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'tab.photo'|trans({}, 'commons') }}</th>
                        <td><img src="{{asset('uploads/' ~ produit.Photo)}}" alt="logo du produit" class="card-img"></td>
                    </tr>
                </tbody>
            </table>
            <a href="{{ path('app_produit_index') }}" class="btn btn-primary">{{ 'btn.back'|trans({}, 'commons') }}</a>
                <a href="{{ path('app_produit_add', {'id': produit.id}) }}" class="btn btn-success">{{ 'show.add'|trans }}</a>
            {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN') %}
                <a href="{{ path('app_produit_edit', {'id': produit.id}) }}" class="btn btn-warning">{{ 'btn.edit'|trans({}, 'commons') }}</a>
                {{ include('produit/_delete_form.html.twig') }}
            {% endif %}
        </div>
    </div>
{% endblock %}